[package]
name = "next-ui"
description = "The desktop GUI for Bottles Next, built with iced on top of next-core."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository = "https://github.com/bottlesdevs/next-ui/"
homepage = ""
categories = [""]
keywords = [""]
exclude = [""]

[dependencies]
async-trait.workspace = true
iced = { version = "0.14", features = ["advanced", "canvas", "svg", "image-without-codecs", "tokio", "linux-theme-detection"] }
tokio-util = { workspace = true, features = ["rt"] }
bottles-core.workspace = true
next-config.workspace = true
next-proto.workspace = true
rust-embed = { version = "8.12.0", features = ["include-exclude"] }
uuid.workspace = true
directories.workspace = true
serde.workspace = true
futures-lite.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true

[features]
debug = ["iced/hot"]
