[package]
name = "next-ui"
version.workspace = true
edition.workspace = true

[dependencies]
iced = { version = "0.14", features = ["advanced", "canvas", "svg", "image-without-codecs", "tokio"] }
tokio = { workspace = true, features = ["fs", "io-util",
  "time"] }
tokio-util.workspace = true
bottles-core.workspace = true
rust-embed = { version = "8.12.0", features = ["include-exclude"] }

[features]
debug = ["iced/hot"]
